name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "Cargo.toml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "Cargo.toml"

env:
  TOOLCHAIN: nightly-2023-10-07

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.TOOLCHAIN }}
      - name: Compile
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose

  rustfmt:
    name: Check Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          components: rustfmt
      - run: cargo fmt --all --check
